plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    maven {
        name = "sonatype-oss-snapshots1"
        url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
    }
    maven {
        name = "xpple"
        url = uri("https://maven.xpple.dev/maven2")
    }
    maven {
        name = "jitpack"
        url = uri("https://jitpack.io")
    }
    maven {
        name = "fallenbreath"
        url = uri('https://maven.fallenbreath.me/releases')
    }
    mavenCentral()
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "edenclient" {
            sourceSet sourceSets.client
        }
    }
}


dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    //Annotations
    implementation project(":EcAnnotations")
    annotationProcessor project(":EcProcessors")
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    //Chat Component API
    implementation include("net.kyori:adventure-api:${project.adventure_version}")
    implementation include("net.kyori:adventure-text-serializer-gson:${project.adventure_version}")
    implementation include("net.kyori:adventure-text-serializer-plain:${project.adventure_version}")

    include implementation("dev.xpple:clientarguments:${project.clientarguments_version}")
    implementation("com.github.sakura-ryoko:malilib:${project.malilib_version}"){
        exclude(group: "me.fallenbreath")
    }

    //yaml
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml:3.1.3'}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}


java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}